replicaCount: 2

image:
  repository: sovereign-app
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  ENVIRONMENT: "k3s-sovereign"
